// projects.js - AUTOMATICALLY GENERATED BY sync_projects.py
const projectsData = [
    {
        "id": "echoes-of-presence",
        "title": "Echoes of Presence",
        "img": "echoesofpresence.png",
        "link": "echoes-of-presence/index.html",
        "tags": [
            "Installation",
            "Creative Tech"
        ],
        "content": "<h1>Echoes of Presence</h1><p>An evolving generative art installation reconciling our relationship to AI worlds.</p>"
    },
    {
        "id": "clanx",
        "title": "ClanX",
        "img": "clanx.png",
        "link": "clanx/index.html",
        "tags": [
            "Product Design",
            "UX"
        ],
        "content": "<h1>ClanX</h1><p>An AI-powered recruitment platform simplifying the path from talent discovery to hire.</p>"
    },
    {
        "id": "unreasonablecube",
        "title": "Unreasonable Cube",
        "img": "unreasonablecube.png",
        "link": "unreasonablecube/index.html",
        "tags": [
            "Installation",
            "Creative Tech"
        ],
        "content": "<h1>Unreasonable Cube</h1><p>A physical AI that maps challenges to multidimensional perspectives through tangible interaction.</p>"
    },
    {
        "id": "lectrixev",
        "title": "Lectrix EV",
        "img": "lectrix.png",
        "link": "lectrixev/",
        "tags": [
            "Product Design",
            "Branding"
        ],
        "content": "<h1>Lectrix EV</h1><p>Reimaging the Lectrix app for a smarter EV scooter experience.</p>"
    },
    {
        "id": "lunaring",
        "title": "Luna Ring",
        "img": "lunaring.png",
        "link": "lunaring/index.html",
        "tags": [
            "UI/UX Design",
            "Health Tech"
        ],
        "content": "<h1>Luna Ring</h1><p>contribution to the development of Luna Ring, a health tracking device merging style with functionality.</p>"
    },
    {
        "id": "viewbuds",
        "title": "Viewbuds",
        "img": "viewbuds.png",
        "link": "viewbuds/index.html",
        "tags": [],
        "content": "<h1>Viewbuds</h1><p>Content coming soon.</p>"
    },
    {
        "id": "bezapp",
        "title": "Bezapp",
        "img": "bezapp.png",
        "link": "https://www.behance.net/gallery/116765115/Events-Management-App-UIUX-Design",
        "tags": [],
        "content": "<h1>Bezapp</h1><p>Content coming soon.</p>"
    },
    {
        "id": "doodleforest",
        "title": "Doodle Forest",
        "img": "doodleforest.png",
        "link": "doodleforest/index.html",
        "tags": [
            "Creative Tech",
            "UX"
        ],
        "content": "<h1>Doodle Forest</h1><p>Plant flora and spawn fauna in a generative 10x10 grid using the Google Quick Draw dataset.</p>"
    },
    {
        "id": "gudz",
        "title": "Gudz",
        "img": "gudz.png",
        "link": "https://www.behance.net/gallery/186363817/Logistics-CMS-Delivery-App",
        "tags": [],
        "content": "<h1>Gudz</h1><p>Content coming soon.</p>"
    },
    {
        "id": "inka",
        "title": "Inka",
        "img": "lectrix.png",
        "link": "inka/index.html",
        "tags": [],
        "content": "<h1>Inka</h1><p>Content coming soon.</p>"
    },
    {
        "id": "oneplus",
        "title": "OnePlus OxygenOS 12",
        "img": "oneplus.png",
        "link": "oneplus/index.html",
        "tags": [
            "Product Design",
            "UI/UX"
        ],
        "content": "<h1>OnePlus OxygenOS 12</h1><p>Enhancing the Work-Life Balance feature and system services in OxygenOS 12 at OnePlus.</p>"
    }
];
const carouselOrder = ["lectrixev", "oneplus", "unreasonablecube", "viewbuds", "clanx", "echoes-of-presence"];
