// projects.js - AUTOMATICALLY GENERATED BY sync_projects.py
const projectsData = [
    {
        "id": "clanx",
        "title": "ClanX",
        "img": "clanx.png",
        "gridImg": "clanx.png",
        "link": "clanx/",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>ClanX</h1><p>An AI-powered recruitment platform simplifying the path from talent discovery to hire.</p>"
    },
    {
        "id": "lectrix-ev",
        "title": "Lectrix EV",
        "img": "lectrix.png",
        "gridImg": "lectrix.png",
        "link": "lectrix-ev/",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Lectrix EV</h1><p>Reimaging the Lectrix app for a smarter EV scooter experience.</p>"
    },
    {
        "id": "echoes-of-presence",
        "title": "Echoes of Presence",
        "img": "echoesofpresence.png",
        "gridImg": "echoesofpresence.png",
        "link": "echoes-of-presence/",
        "tags": [
            "Creative Tech"
        ],
        "content": "<h1>Echoes of Presence</h1><p>Content coming soon.</p>"
    },
    {
        "id": "unreasonablecube",
        "title": "Unreasonable Cube",
        "img": "unreasonablecube.png",
        "gridImg": "unreasonablecube_Claude.png",
        "link": "unreasonablecube/",
        "tags": [
            "Creative Tech"
        ],
        "content": "<h1>Unreasonable Cube</h1><p>Content coming soon.</p>"
    },
    {
        "id": "lunaring",
        "title": "Luna Ring",
        "img": "lunaring.png",
        "gridImg": "lunaring.png",
        "link": "lunaring/",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Luna Ring</h1><p>contribution to the development of Luna Ring, a health tracking device merging style with functionality.</p>"
    },
    {
        "id": "viewbuds",
        "title": "Viewbuds",
        "img": "echoesofpresence.png",
        "gridImg": "echoesofpresence.png",
        "link": "viewbuds/",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Viewbuds</h1><p>Content coming soon.</p>"
    },
    {
        "id": "bezapp",
        "title": "Bezapp",
        "img": "bezapp.png",
        "gridImg": "bezapp.png",
        "link": "https://www.behance.net/gallery/116765115/Events-Management-App-UIUX-Design",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Bezapp</h1><p>Content coming soon.</p>"
    },
    {
        "id": "doodleforest",
        "title": "Doodle Forest",
        "img": "doodleforest.png",
        "gridImg": "doodleforest.png",
        "link": "doodleforest/",
        "tags": [
            "Creative Tech"
        ],
        "content": "<h1>Doodle Forest</h1><p>Plant flora and spawn fauna in a generative 10x10 grid using the Google Quick Draw dataset.</p>"
    },
    {
        "id": "gudz",
        "title": "Gudz",
        "img": "gudz.png",
        "gridImg": "gudz.png",
        "link": "https://www.behance.net/gallery/186363817/Logistics-CMS-Delivery-App",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Gudz</h1><p>Content coming soon.</p>"
    },
    {
        "id": "oneplus",
        "title": "OnePlus OxygenOS 12",
        "img": "oneplus.png",
        "gridImg": "oneplus.png",
        "link": "oneplus/",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>OnePlus OxygenOS 12</h1><p>Enhancing the Work-Life Balance feature and system services in OxygenOS 12 at OnePlus.</p>"
    },
    {
        "id": "permanence-of-decay",
        "title": "Permanence of Decay",
        "img": "permanenceofdecay.png",
        "gridImg": "permanenceofdecay.png",
        "link": "permanence-of-decay/",
        "tags": [
            "Creative Tech"
        ],
        "content": "<h1>Permanence of Decay</h1><p>An interactive system of controlled erosion reconciling our relationship to digital past through bit rot.</p>"
    }
];
const carouselOrder = ["echoes-of-presence", "unreasonablecube", "oneplus", "viewbuds", "lectrix-ev", "clanx"];
