// projects.js - AUTOMATICALLY GENERATED BY sync_projects.py
const projectsData = [
    {
        "id": "clanx",
        "title": "ClanX",
        "img": "clanx.png",
        "link": "projects/clanx/index.html",
        "tags": [
            "Product Design",
            "UX"
        ],
        "content": "<h1>ClanX</h1><p>An AI-powered recruitment platform simplifying the path from talent discovery to hire.</p>"
    },
    {
        "id": "echoes-of-presence",
        "title": "Echoes of Presence",
        "img": "echoesofpresence.png",
        "link": "projects/echoes-of-presence/index.html",
        "tags": [
            "Installation",
            "Creative Tech"
        ],
        "content": "<h1>Echoes of Presence</h1><p>An evolving generative art installation reconciling our relationship to AI worlds.</p>"
    },
    {
        "id": "lectrixEV",
        "title": "Lectrix EV",
        "img": "lectrix.png",
        "link": "projects/lectrixEV/index.html",
        "tags": [
            "Product Design",
            "Branding"
        ],
        "content": "<h1>Lectrix EV</h1><p>Reimaging the Lectrix app for a smarter EV scooter experience.</p>"
    },
    {
        "id": "lunaring",
        "title": "Lunaring",
        "img": "lunaring.png",
        "link": "projects/lunaring/index.html",
        "tags": [],
        "content": "<h1>Lunaring</h1><p>Content coming soon.</p>"
    },
    {
        "id": "unreasonablecube",
        "title": "Unreasonable Cube",
        "img": "unreasonablecube.png",
        "link": "projects/unreasonablecube/index.html",
        "tags": [
            "Installation",
            "Creative Tech"
        ],
        "content": "<h1>Unreasonable Cube</h1><p>A physical AI that maps challenges to multidimensional perspectives through tangible interaction.</p>"
    },
    {
        "id": "doodleforest",
        "title": "Doodle Forest",
        "img": "doodleforest.png",
        "link": "projects/doodleforest/index.html",
        "tags": [
            "Creative Tech",
            "UX"
        ],
        "content": "<h1>Doodle Forest</h1><p>Plant flora and spawn fauna in a generative 10x10 grid using the Google Quick Draw dataset.</p>"
    },
    {
        "id": "gudz",
        "title": "Gudz",
        "img": "echoesofpresence.png",
        "link": "projects/gudz/index.html",
        "tags": [],
        "content": "<h1>Gudz</h1><p>Content coming soon.</p>"
    },
    {
        "id": "inka",
        "title": "Inka",
        "img": "lectrix.png",
        "link": "projects/inka/index.html",
        "tags": [],
        "content": "<h1>Inka</h1><p>Content coming soon.</p>"
    },
    {
        "id": "oneplus",
        "title": "Oxygen",
        "img": "lectrix.png",
        "link": "projects/oneplus/index.html",
        "tags": [],
        "content": "<h1>Oxygen</h1><p>Content coming soon.</p>"
    },
    {
        "id": "viewbuds",
        "title": "Viewbuds",
        "img": "echoesofpresence.png",
        "link": "projects/viewbuds/index.html",
        "tags": [],
        "content": "<h1>Viewbuds</h1><p>Content coming soon.</p>"
    }
];
