import os
import re
import json

# Configuration
PROJECTS_DIR = '.'
PROJECTS_JS_FILE = 'projects.js'
DEFAULT_COVER = 'echoesofpresence.png'
BLACKLIST = ['.git', 'about', 'work', 'play', 'covers', 'common', '.DS_Store']

def extract_meta(html_content, name):
    match = re.search(f'<meta name="{name}" content="(.*?)"', html_content)
    return match.group(1) if match else None

def extract_title(html_content):
    match = re.search('<title>(.*?)</title>', html_content)
    if match:
        title = match.group(1).split('|')[0].strip()
        return title
    return "Untitled Project"

def sync():
    projects_data = []
    
    # 1. GRID PRIORITY (Order on the Work page)
    GRID_PRIORITY = [
        'echoes-of-presence',
        'clanx',
        'unreasonablecube',
        'lectrixev',
        'lunaring',
        'viewbuds',        
    ]

    # 2. CAROUSEL PRIORITY (Order and selection for the Home page)
    CAROUSEL_PRIORITY = [
        
        'lectrixev',
        'oneplus',
        'unreasonablecube',
        'viewbuds',
        'clanx',
        'echoes-of-presence'
    ]
    
    # Sort folders for GRID based on GRID_PRIORITY
    folders = [f for f in os.listdir(PROJECTS_DIR) 
               if os.path.isdir(os.path.join(PROJECTS_DIR, f)) 
               and f not in BLACKLIST]
    
    def sort_key(folder):
        if folder in GRID_PRIORITY:
            return (0, GRID_PRIORITY.index(folder))
        else:
            return (1, folder.lower())
            
    folders.sort(key=sort_key)

    for folder in folders:
        index_path = os.path.join(PROJECTS_DIR, folder, 'index.html')
        if not os.path.exists(index_path):
            continue
            
        with open(index_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        title = extract_title(content)
        img = extract_meta(content, 'project-img')
        tags_raw = extract_meta(content, 'project-tags')
        tags = [t.strip() for t in tags_raw.split(',')] if tags_raw else []
        description = extract_meta(content, 'project-description') or "Content coming soon."
        external_link = extract_meta(content, 'project-link')
        
        if not img:
            for ext in ['png', 'jpg', 'jpeg', 'webp']:
                if os.path.exists(os.path.join(PROJECTS_DIR, folder, f'cover.{ext}')):
                    img = f'{folder}/cover.{ext}'
                    break
        
        if not img:
            img = DEFAULT_COVER
            
        projects_data.append({
            "id": folder,
            "title": title,
            "img": img,
            "link": external_link if external_link else f"{folder}/index.html",
            "tags": tags,
            "content": f"<h1>{title}</h1><p>{description}</p>"
        })

    js_output = f"const projectsData = {json.dumps(projects_data, indent=4)};\n"
    js_output += f"const carouselOrder = {json.dumps(CAROUSEL_PRIORITY)};\n"
    
    with open(PROJECTS_JS_FILE, 'w', encoding='utf-8') as f:
        f.write("// projects.js - AUTOMATICALLY GENERATED BY sync_projects.py\n")
        f.write(js_output)
        
    print(f"Successfully synced {len(projects_data)} projects and carousel order to {PROJECTS_JS_FILE}")

if __name__ == "__main__":
    sync()
