import os
import re
import json

# Configuration
PROJECTS_DIR = 'projects'
PROJECTS_JS_FILE = 'projects.js'
DEFAULT_COVER = 'echoesofpresence.png' # Fallback

def extract_meta(html_content, name):
    match = re.search(f'<meta name="{name}" content="(.*?)"', html_content)
    return match.group(1) if match else None

def extract_title(html_content):
    match = re.search('<title>(.*?)</title>', html_content)
    if match:
        title = match.group(1).split('|')[0].strip()
        return title
    return "Untitled Project"

def sync():
    projects_data = []
    
    if not os.path.exists(PROJECTS_DIR):
        print(f"Error: {PROJECTS_DIR} directory not found.")
        return

    # Sort directories by name (or potentially by date if we wanted)
    project_folders = sorted([f for f in os.listdir(PROJECTS_DIR) if os.path.isdir(os.path.join(PROJECTS_DIR, f))])

    for folder in project_folders:
        index_path = os.path.join(PROJECTS_DIR, folder, 'index.html')
        if not os.path.exists(index_path):
            continue
            
        with open(index_path, 'r', encoding='utf-8') as f:
            content = f.read()
            
        title = extract_title(content)
        # Look for cover image in meta tag, otherwise check for cover.png/jpg
        img = extract_meta(content, 'project-img')
        
        if not img:
            for ext in ['png', 'jpg', 'jpeg', 'webp']:
                if os.path.exists(os.path.join(PROJECTS_DIR, folder, f'cover.{ext}')):
                    img = f'../projects/{folder}/cover.{ext}'
                    break
        
        # If still no image, use the one from projects.js if we can find it, or fallback
        if not img:
            img = DEFAULT_COVER # We could improve this by parsing current projects.js first
            
        # Extract content between <!-- START_CONTENT --> and <!-- END_CONTENT --> if present
        # Or just use the h1 and first p as a teaser? 
        # Actually, let's keep it simple: just the link and metadata for now.
        
        projects_data.append({
            "id": folder,
            "title": title,
            "img": img,
            "link": f"projects/{folder}/index.html",
            "content": f"<h1>{title}</h1><p>Content loaded from project folder.</p>" # Placeholder
        })

    # Read the current projects.js to preserve 'content' if it's there?
    # Actually, the user wants it ALMOST ALL from the folder.
    # Maybe we should have a 'content.html' file in each folder?
    # For now, let's just update the list and link.

    js_output = f"const projectsData = {json.dumps(projects_data, indent=4)};\n"
    
    with open(PROJECTS_JS_FILE, 'w', encoding='utf-8') as f:
        f.write("// projects.js - AUTOMATICALLY GENERATED BY sync_projects.py\n")
        f.write(js_output)
        
    print(f"Successfully synced {len(projects_data)} projects to {PROJECTS_JS_FILE}")

if __name__ == "__main__":
    sync()
