// projects.js - AUTOMATICALLY GENERATED BY sync_projects.py
const projectsData = [
    {
        "id": "clanx",
        "title": "ClanX",
        "year": "2024",
        "img": "clanx.png",
        "gridImg": "clanx.png",
        "galleryLayout": "3",
        "galleryImages": [
            {
                "src": "../clanx/assets/1.png",
                "ratio": "ratio-cube"
            },
            {
                "src": "../clanx/assets/2.png",
                "ratio": "ratio-cube"
            },
            {
                "src": "../clanx/assets/3.png",
                "ratio": "ratio-cube"
            }
        ],
        "link": "clanx/",
        "externalLink": "",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>ClanX</h1><p>An AI-powered recruitment platform simplifying the path from talent discovery to hire.</p>"
    },
    {
        "id": "lectrix-ev",
        "title": "Lectrix EV",
        "year": "2024",
        "img": "lectrix.png",
        "gridImg": "lectrix.png",
        "galleryLayout": "3",
        "galleryImages": [
            {
                "src": "../lectrix-ev/assets/1.png",
                "ratio": "ratio-cube"
            },
            {
                "src": "../lectrix-ev/assets/2.png",
                "ratio": "ratio-cube"
            },
            {
                "src": "../lectrix-ev/assets/3.png",
                "ratio": "ratio-cube"
            }
        ],
        "link": "lectrix-ev/",
        "externalLink": "",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Lectrix EV</h1><p>Reimaging the Lectrix app for a smarter EV scooter experience.</p>"
    },
    {
        "id": "echoes-of-presence",
        "title": "Echoes of Presence",
        "year": "2023",
        "img": "echoesofpresence.png",
        "gridImg": "echoesofpresence.png",
        "galleryLayout": "2",
        "galleryImages": [
            {
                "src": "../echoes-of-presence/assets/1.jpeg",
                "ratio": "ratio-cube"
            },
            {
                "src": "../echoes-of-presence/assets/3.png",
                "ratio": "ratio-cube"
            }
        ],
        "link": "echoes-of-presence/",
        "externalLink": "",
        "tags": [
            "Creative Tech"
        ],
        "content": "<h1>Echoes of Presence</h1><p>An evolving generative art installation reconciling our relationship to AI worlds.</p>"
    },
    {
        "id": "unreasonablecube",
        "title": "Unreasonable Cube",
        "year": "2026",
        "img": "unreasonablecube.png",
        "gridImg": "unreasonablecube_Claude.png",
        "galleryLayout": "1",
        "galleryImages": [
            {
                "src": "../covers/unreasonablecube_Claude.png",
                "ratio": "ratio-cube"
            }
        ],
        "link": "unreasonablecube/",
        "externalLink": "",
        "tags": [
            "Creative Tech"
        ],
        "content": "<h1>Unreasonable Cube</h1><p>A physical AI that maps challenges to multidimensional perspectives through tangible interaction.</p>"
    },
    {
        "id": "lunaring",
        "title": "Luna Ring",
        "year": "2023",
        "img": "lunaring.png",
        "gridImg": "lunaring.png",
        "galleryLayout": "2",
        "galleryImages": [
            {
                "src": "../lunaring/assets/2.png",
                "ratio": "ratio-cube"
            },
            {
                "src": "../lunaring/assets/4.png",
                "ratio": "ratio-cube"
            }
        ],
        "link": "lunaring/",
        "externalLink": "",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Luna Ring</h1><p>contribution to the development of Luna Ring, a health tracking device merging style with functionality.</p>"
    },
    {
        "id": "viewbuds",
        "title": "Viewbuds",
        "year": "2025",
        "img": "../covers/viewbuds.png",
        "gridImg": "../covers/viewbuds.png",
        "galleryLayout": "1",
        "galleryImages": [
            {
                "src": "../covers/viewbuds.png",
                "ratio": "ratio-landscape"
            }
        ],
        "link": "viewbuds/",
        "externalLink": "",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Viewbuds</h1><p>Content coming soon.</p>"
    },
    {
        "id": "bezapp",
        "title": "Bezapp",
        "year": "",
        "img": "bezapp.png",
        "gridImg": "bezapp.png",
        "galleryLayout": "1",
        "galleryImages": [
            {
                "src": "../bezapp/bezapp.png",
                "ratio": "ratio-landscape"
            }
        ],
        "link": "https://www.behance.net/gallery/116765115/Events-Management-App-UIUX-Design",
        "externalLink": "https://www.behance.net/gallery/116765115/Events-Management-App-UIUX-Design",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Bezapp</h1><p>Content coming soon.</p>"
    },
    {
        "id": "doodleforest",
        "title": "Doodle Forest",
        "year": "2025",
        "img": "doodleforest.png",
        "gridImg": "doodleforest.png",
        "galleryLayout": "1",
        "galleryImages": [
            {
                "src": "../doodleforest/doodleforest.png",
                "ratio": "ratio-landscape"
            }
        ],
        "link": "doodleforest/",
        "externalLink": "",
        "tags": [
            "Creative Tech"
        ],
        "content": "<h1>Doodle Forest</h1><p>Plant flora and spawn fauna in a generative 10x10 grid using the Google Quick Draw dataset.</p>"
    },
    {
        "id": "gudz",
        "title": "Gudz",
        "year": "",
        "img": "gudz.png",
        "gridImg": "gudz.png",
        "galleryLayout": "1",
        "galleryImages": [
            {
                "src": "../gudz/gudz.png",
                "ratio": "ratio-landscape"
            }
        ],
        "link": "https://www.behance.net/gallery/186363817/Logistics-CMS-Delivery-App",
        "externalLink": "https://www.behance.net/gallery/186363817/Logistics-CMS-Delivery-App",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>Gudz</h1><p>Content coming soon.</p>"
    },
    {
        "id": "New Portfolio",
        "title": "Pranav Chaparala \u2014 Designer & Creative Technologist",
        "year": "",
        "img": "echoesofpresence.png",
        "gridImg": "echoesofpresence.png",
        "galleryLayout": "1",
        "galleryImages": [
            {
                "src": "../covers/echoesofpresence.png",
                "ratio": "ratio-landscape"
            }
        ],
        "link": "New Portfolio/",
        "externalLink": "",
        "tags": [],
        "content": "<h1>Pranav Chaparala \u2014 Designer & Creative Technologist</h1><p>Content coming soon.</p>"
    },
    {
        "id": "oneplus",
        "title": "OnePlus OxygenOS 12",
        "year": "2021",
        "img": "oneplus.png",
        "gridImg": "oneplus.png",
        "galleryLayout": "1",
        "galleryImages": [
            {
                "src": "../oneplus/oneplus.png",
                "ratio": "ratio-landscape"
            }
        ],
        "link": "oneplus/",
        "externalLink": "",
        "tags": [
            "Product Design"
        ],
        "content": "<h1>OnePlus OxygenOS 12</h1><p>Enhancing the Work-Life Balance feature and system services in OxygenOS 12 at OnePlus.</p>"
    },
    {
        "id": "permanence-of-decay",
        "title": "Permanence of Decay",
        "year": "2026",
        "img": "permanenceofdecay.png",
        "gridImg": "permanenceofdecay.png",
        "galleryLayout": "2",
        "galleryImages": [
            {
                "src": "../permanence-of-decay/assets/IMG_0653-edited.jpg",
                "ratio": "ratio-cube"
            },
            {
                "src": "../permanence-of-decay/assets/IMG_0652-edited-scaled.jpg",
                "ratio": "ratio-cube"
            }
        ],
        "link": "permanence-of-decay/",
        "externalLink": "",
        "tags": [
            "Creative Tech"
        ],
        "content": "<h1>Permanence of Decay</h1><p>Permanence of Decay challenges our culture of infinite digital storage by treating data like a mortal, living thing. While computers normally act as permanent vaults, this installation introduces a finite lifespan to a photographic archive, causing images to age and break down over time.</p>"
    }
];
const carouselOrder = ["echoes-of-presence", "unreasonablecube", "oneplus", "viewbuds", "lectrix-ev", "clanx"];
